version: '3.7'

volumes:
  bundle: {}
  npm: {}

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - '.:/app:delegated'
      - '~/.ssh:/root/.ssh:delegated'
      - 'bundle:/usr/local/bundle'
      - 'npm:/app/node_modules'
